### ISSUE TITLE
Code review stuff

### ISSUE THREAD

**Issue by amirrajan** [amirrajan/mokepon#3]
Stuff that @rusty-software wrote to me. Putting it here since this is a better medium for sharing code and stuff:

The good news: I think the code looks pretty good. The bad news: I’m a notoriously lenient code-reviewer. 😉 If you want something more detailed/stringent, we can ask Tim to have a look.

My thoughts are:

• Just curious — why did you go with sablono instead of reagent?

• Consider renaming “core” to something else (I use “main,” but ymmv). This is most useful for stacktrace examination/debugging

• I’m using Intellij with the Cursive plug-in for lots of reasons, the least of which is it helps me find unused vars. I don’t think there’s a free version anymore (single license is $99, I think). All of this to say: there’s a fair amount of unused code sprinkled throughout. Some of it looks debuggy, but other bits look truly crufty. If you don’t have a good plug-in to help you find those spots, it might be worth pairing with someone that has Cursive to clean up.

• I like the idea of running tests on refresh! The state deref is normally an atom/ref, so the function call to get it threw me a little when I first saw it. I wish I could think of a more elegant way to fix that (dynamic binding, maybe?), but it might not be worth it either.

• The “worst” thing I saw on the first pass was actually not very prolific: updating the state via swap in a non-thread-safe way. This isn't a big deal currently, since there shouldn't be any competing threads. 

Atoms are intended to be thread-safe, but only if you swap! them correctly, which you did most of the time. There were a couple of spots where you were swapping a value but in the handler function, were deref-ing the state to get some other value from the atom. If another thread updates that other value while you’re swapping, you’ll get the _new_ value instead of the value at the time you started the swap, which will lead to unexpected results at best.

I’m probably not explaining this well, so try this in a clojure repl. Hopefully it’ll clarify things:

```
user=> (def app-state (atom {:counter 0}))
#'user/app-state
user=> (defn associator [state new-val] (Thread/sleep 10) (assoc state :counter new-val))
#'user/associator
user=> (defn unsafe-swap [a-state] (swap! a-state associator (inc (:counter @a-state))))
#'user/unsafe-swap
user=> (future (dotimes [_ 10000] (unsafe-swap app-state)))
#object[clojure.core$future_call$reify__6962 0x9a85f26 {:status :pending, :val nil}]
user=> (future (dotimes [_ 10000] (unsafe-swap app-state)))
#object[clojure.core$future_call$reify__6962 0x163507cd {:status :pending, :val nil}]
user=> (future (dotimes [_ 10000] (unsafe-swap app-state)))
#object[clojure.core$future_call$reify__6962 0x73f0af2e {:status :pending, :val nil}]
user=> @app-state
{:counter 277}
user=> @app-state
{:counter 350}
user=> @app-state
{:counter 400}
user=> @app-state
{:counter 439}
user=> @app-state
{:counter 464}
user=> @app-state
{:counter 493}
user=> @app-state
{:counter 510}
user=> @app-state
{:counter 535}
user=> @app-state
{:counter 556}
user=> @app-state
{:counter 585}
user=> @app-state
{:counter 603}
user=> @app-state
{:counter 621}
user=> @app-state
{:counter 561}
user=> @app-state
{:counter 587}
user=> @app-state
{:counter 679}
```

**Comment by amirrajan** [comment]
>Just curious — why did you go with sablono instead of reagent?

I've done quite a bit of React/ES2015 and wanted to pull in "just enough" to move to ClojureScript (and provide an evolutionary process for other JS devs to move there either). The `Container` pattern (where a top level empty react components holds all the props, then passes everything down) is a common approach in vanilla React world. I wanted to capture that in ClojureScript and see what it looks like... so far I'm happy with it.

In short. Didn't need reagent, a thin layer around component construction, an atom, and the container pattern seem sufficient for now.

>Consider renaming “core” to something else (I use “main,” but ymmv). This is most useful for stacktrace examination/debugging

Still trying to figure out a good way to split things up. But I agree, `main` (or `index` like the cool react kids do it) would be a better name for that file.

>there’s a fair amount of unused code sprinkled throughout. [...] but other bits look truly crufty.

I prefer to call them battle scars. But yes, I'll do a full audit of all that as soon as my test coverage is a bit better.

>I like the idea of running tests on refresh! The state deref is normally an atom/ref, so the function call to get it threw me a little

🎉 , I'm still looking for a better way to do that myself.

>updating the state via swap in a non-thread-safe way.

My clojure noobness showing through, I'll read up on this stuff and see if I can do a better job with that.

**Comment by rusty-software** [comment]
👍

**Comment by amirrajan** [comment]
Did some stuff, want to do another review?
